name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flet
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # 5. APK жинау (Жаңа нұсқалар үшін ең сенімді әдіс)
      - name: Flet Build APK
        run: |
          echo y | flet build apk --project "SatbayevENT" --product "№63 Қ.Сатбаев" --org "com.satbayev.ent" -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Satbayev-APK-Release
          path: build/apk/app-release.apk
